export interface StateData {
  nameGe: string;
  nameEn: string;
  abbr: string;
}

export const usStates: StateData[] = [
  { nameGe: 'ალაბამა', nameEn: 'Alabama', abbr: 'AL' },
  { nameGe: 'ალასკა', nameEn: 'Alaska', abbr: 'AK' },
  { nameGe: 'არიზონა', nameEn: 'Arizona', abbr: 'AZ' },
  { nameGe: 'არკანზასი', nameEn: 'Arkansas', abbr: 'AR' },
  { nameGe: 'კალიფორნია', nameEn: 'California', abbr: 'CA' },
  { nameGe: 'კოლორადო', nameEn: 'Colorado', abbr: 'CO' },
  { nameGe: 'კონექტიკუტი', nameEn: 'Connecticut', abbr: 'CT' },
  { nameGe: 'დელავერი', nameEn: 'Delaware', abbr: 'DE' },
  { nameGe: 'ფლორიდა', nameEn: 'Florida', abbr: 'FL' },
  { nameGe: 'ჯორჯია', nameEn: 'Georgia', abbr: 'GA' },
  { nameGe: 'ჰავაი', nameEn: 'Hawaii', abbr: 'HI' },
  { nameGe: 'აიდაჰო', nameEn: 'Idaho', abbr: 'ID' },
  { nameGe: 'ილინოისი', nameEn: 'Illinois', abbr: 'IL' },
  { nameGe: 'ინდიანა', nameEn: 'Indiana', abbr: 'IN' },
  { nameGe: 'აიოვა', nameEn: 'Iowa', abbr: 'IA' },
  { nameGe: 'კანზასი', nameEn: 'Kansas', abbr: 'KS' },
  { nameGe: 'კენტუკი', nameEn: 'Kentucky', abbr: 'KY' },
  { nameGe: 'ლუიზიანა', nameEn: 'Louisiana', abbr: 'LA' },
  { nameGe: 'მენი', nameEn: 'Maine', abbr: 'ME' },
  { nameGe: 'მერილენდი', nameEn: 'Maryland', abbr: 'MD' },
  { nameGe: 'მასაჩუსეტსი', nameEn: 'Massachusetts', abbr: 'MA' },
  { nameGe: 'მიჩიგანი', nameEn: 'Michigan', abbr: 'MI' },
  { nameGe: 'მინესოტა', nameEn: 'Minnesota', abbr: 'MN' },
  { nameGe: 'მისისიპი', nameEn: 'Mississippi', abbr: 'MS' },
  { nameGe: 'მისური', nameEn: 'Missouri', abbr: 'MO' },
  { nameGe: 'მონტანა', nameEn: 'Montana', abbr: 'MT' },
  { nameGe: 'ნებრასკა', nameEn: 'Nebraska', abbr: 'NE' },
  { nameGe: 'ნევადა', nameEn: 'Nevada', abbr: 'NV' },
  { nameGe: 'ნიუ-ჰემფშირი', nameEn: 'New Hampshire', abbr: 'NH' },
  { nameGe: 'ნიუ-ჯერსი', nameEn: 'New Jersey', abbr: 'NJ' },
  { nameGe: 'ნიუ-მექსიკო', nameEn: 'New Mexico', abbr: 'NM' },
  { nameGe: 'ნიუ-იორკი', nameEn: 'New York', abbr: 'NY' },
  { nameGe: 'ჩრდილოეთ კაროლინა', nameEn: 'North Carolina', abbr: 'NC' },
  { nameGe: 'ჩრდილოეთ დაკოტა', nameEn: 'North Dakota', abbr: 'ND' },
  { nameGe: 'ოჰაიო', nameEn: 'Ohio', abbr: 'OH' },
  { nameGe: 'ოკლაჰომა', nameEn: 'Oklahoma', abbr: 'OK' },
  { nameGe: 'ორეგონი', nameEn: 'Oregon', abbr: 'OR' },
  { nameGe: 'პენსილვანია', nameEn: 'Pennsylvania', abbr: 'PA' },
  { nameGe: 'როდ-აილენდი', nameEn: 'Rhode Island', abbr: 'RI' },
  { nameGe: 'სამხრეთ კაროლინა', nameEn: 'South Carolina', abbr: 'SC' },
  { nameGe: 'სამხრეთ დაკოტა', nameEn: 'South Dakota', abbr: 'SD' },
  { nameGe: 'ტენესი', nameEn: 'Tennessee', abbr: 'TN' },
  { nameGe: 'ტეხასი', nameEn: 'Texas', abbr: 'TX' },
  { nameGe: 'იუტა', nameEn: 'Utah', abbr: 'UT' },
  { nameGe: 'ვერმონტი', nameEn: 'Vermont', abbr: 'VT' },
  { nameGe: 'ვირჯინია', nameEn: 'Virginia', abbr: 'VA' },
  { nameGe: 'ვაშინგტონი', nameEn: 'Washington', abbr: 'WA' },
  { nameGe: 'დასავლეთ ვირჯინია', nameEn: 'West Virginia', abbr: 'WV' },
  { nameGe: 'ვისკონსინი', nameEn: 'Wisconsin', abbr: 'WI' },
  { nameGe: 'ვაიომინგი', nameEn: 'Wyoming', abbr: 'WY' },
  { nameGe: 'კოლუმბიის ოლქი (ვაშინგტონი)', nameEn: 'District of Columbia', abbr: 'DC' }
];
